### ISSUE TITLE
HTML does not meet standard W3C Markup Validation Service

### ISSUE THREAD

**Issue by damisparks** [sepidehshafiei/portfolio-Sepideh#1]
Hi @sepidehshafiei 

I validated your HTML structure through [W3C Markup Validation Service](https://validator.w3.org/#validate_by_input). However, it does not might specification. 

Copy and paste the code inside your `index.html` [here](https://validator.w3.org/#validate_by_input) for validation.

Kindly check the errors and fix them accordingly.

**Comment by sepidehshafiei** [comment]
@damisparks Thanks I am working on this.
